CREATE SCHEMA MYSCHEMA;

CREATE TABLE MYSCHEMA.S_PERSON(
  ID_PERSON NUMBER(12) PRIMARY KEY,
  DS_NAME VARCHAR2(100),
  SALARY NUMBER(9,2) NOT NULL,
  birthdate DATE
);

CREATE SEQUENCE MYSCHEMA.PERSON_SEQ;